name: rrg
description: "Car rental"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  firebase_pagination: ^4.0.1
  cloud_firestore: ^5.0.2

  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  cryptlib_2_0: ^0.0.3
  intl: any

  lottie: ^3.1.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
