// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbra31kPSTGrxpL61U9X_HIezigPNPiho',
    appId: '1:422535031673:web:8c9b486ce29c011e181da8',
    messagingSenderId: '422535031673',
    projectId: 'r-r-g-rental-car',
    authDomain: 'r-r-g-rental-car.firebaseapp.com',
    storageBucket: 'r-r-g-rental-car.appspot.com',
    measurementId: 'G-ZRNNKQ4QD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuZk8oPzOllCEouDDl01CQz4Ec0ZB3RFo',
    appId: '1:422535031673:android:61843d24ca1042bd181da8',
    messagingSenderId: '422535031673',
    projectId: 'r-r-g-rental-car',
    storageBucket: 'r-r-g-rental-car.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzpLRyrY0Z60yBkwZqt1ZslUU2t6VWfk',
    appId: '1:422535031673:ios:0c4aab86162d2315181da8',
    messagingSenderId: '422535031673',
    projectId: 'r-r-g-rental-car',
    storageBucket: 'r-r-g-rental-car.appspot.com',
    iosBundleId: 'com.comma.rrg',
  );
}
