import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'app_name': 'Gulf Coast',
          'email': 'Email',
          'name': 'Name',
          'back': 'Back',
          'admin': 'Admin',
          'reset_password': 'Reset Password',
          'please_enter_your_name': 'Please enter your name',
          'password': 'Password',
          'log_in': 'Log In',
          'forgot_password': 'Forgot Password?',
          'dont_have_an_account': 'Don\'t Have An Account?',
          'sign_up': 'Sign Up',
          'already_have_an_account': 'Already Have An Account?',
          'please_enter_a_valid_username': 'Please Enter a valid username',
          'password_length_should_at_least_6_character':
              'Password length should at least 6 characters',
          'error_occured': 'Error occurred',
          'this_email_address_is_already_in_use':
              'This email address is already in use',
          'something_went_wrong': 'Something went wrong',
          'too_many_requests': 'Too many requests',
          'try_again_later': 'Try again later',
          'incorrect_password': 'Incorrect password',
          'try_again': 'Try again',
          'your_account_not_found': 'Your account not found',
          'create_new_account': 'Create new account',
          'wallet': 'Wallet',
          'profile': 'Profile',
          'about_us': 'About US',
          'contact_us': 'Contact US',
          'log_out': 'Log out',
          'attach_file': 'Attach file',
          'message': 'Message',
          'please_enter_your_message': 'Please enter your message',
          'send_message': 'Send Message',
          'we_would_love_to_hear_from_you': 'We would love to hear from you!',
          'sorry': 'Sorry :(',
          'user_not_found': 'User not found',
          'success': 'Success :)',
          'opps': 'Opps :|',
          'start': 'Start',
          'dashboard': 'Dashboard',
          'users': 'Users',
          'cars': 'Cars',
          'enter_vin': 'Enter VIN',
          'thanks_for_your_message,we_will_reply_as_soon_as_possible':
              'Thaks for your message, we will reply as soon as possible',
          'no_data_found': 'No data found',
          'vin': 'VIN',
          'users_count': 'Users count',
          'vehicles': 'Vehicles',
          'vehicles_count': 'Vehicles count',
          'logout': 'Logout',
          'make': 'Make',
          'model': 'Model',
          'year': 'Year',
          'status': 'Status',
          'fuel_type': 'Fuel Type',
          'vin_should_at_least_17_characters':
              'VIN should at least 17 characters',
          'something_went_wrong_try_again_later_or_try_another_vin':
              'Something went wrong, try again or try another VIN',
          'add_new_user': 'Add new user',
          'all': 'All',
          'new': 'New',
          'loaded': 'Loaded',
          'shipped': 'Shipped',
          'at_terminal': 'At terminal',
          'booked': 'Booked',
          'delivered': 'Delivered',
          'unloaded': 'Unloaded',
          'released_to_client': 'Released to client',
          'username': 'Username',
          'submit': 'Submit',
          'user_added': 'User added',
          'generate_data_from_name': 'Generate data from name',
          'username_already_exist': 'Username already exist',
          'owner': 'Owner',
          'loading': 'Loading...',
          'select_user_for_this_car': 'Select user for this car',
          'are_you_sure_you_want_to_assign': 'Are you sure you want to assign',
          'to': 'To',
          'yes': 'Yes',
          'no': 'No',
          'aed': 'AED',
          'for_sale': 'For sale',
          'continue_as_guest': 'Continue as guest',
          'auction': 'Auction',
          'filter': 'Filter',
          'car_for_sale': 'Car for sale',
          'select': 'Select',
          'select_year': 'Select year',
          'vehicle_added': 'Vehicle added',
          'contact': 'Contact',
          'update': 'Update',
          'set_price': 'Set price',
          'enter_price': 'Enter price',
          'lot': 'LOT',
          'usa': 'USA',
          'aqaba': 'Aqaba',
          'umm_qasr': 'Umm Qasr',
          'jabal_ali': 'Jabal Ali',
          'provider': 'Provider',
          'settings': 'Settings',
          'delete_account': 'Delete account',
          'company': 'Company',
          'phone': 'Phone',
          'destination': 'Destination',
          'please_fill_all_fields': 'Please fill all fields',
          'attach_invoice': 'Attach invoice',
          'the_car_is_already_exists': 'The car is already exists',
        },
      };
}
